Download the data of [FitBit Fitness Tracker Data](https://www.kaggle.com/datasets/nurudeenabdulsalaam/fitbit-fitness-tracker-data?select=dailyIntensities_merged.csv) (click to follow the link).    

In [60]:
import pandas as pd

In [61]:
fit = pd.read_csv('dailyIntensities_merged.csv')
fit.head()

Id ActivityDay  SedentaryMinutes  LightlyActiveMinutes  \
0  1503960366   4/12/2016               728                   328   
1  1503960366   4/13/2016               776                   217   
2  1503960366   4/14/2016              1218                   181   
3  1503960366   4/15/2016               726                   209   
4  1503960366   4/16/2016               773                   221   

   FairlyActiveMinutes  VeryActiveMinutes  SedentaryActiveDistance  \
0                   13                 25                      0.0   
1                   19                 21                      0.0   
2                   11                 30                      0.0   
3                   34                 29                      0.0   
4                   10                 36                      0.0   

   LightActiveDistance  ModeratelyActiveDistance  VeryActiveDistance  
0                 6.06                      0.55                1.88  
1                 4.71                      0.69                1.57  
2                 3.91                      0.40                2.44  
3                 2.83                      1.26                2.14  
4                 5.04                      0.41                2.71

In [62]:
fit.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 940 entries, 0 to 939
Data columns (total 10 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   Id                        940 non-null    int64  
 1   ActivityDay               940 non-null    object 
 2   SedentaryMinutes          940 non-null    int64  
 3   LightlyActiveMinutes      940 non-null    int64  
 4   FairlyActiveMinutes       940 non-null    int64  
 5   VeryActiveMinutes         940 non-null    int64  
 6   SedentaryActiveDistance   940 non-null    float64
 7   LightActiveDistance       940 non-null    float64
 8   ModeratelyActiveDistance  940 non-null    float64
 9   VeryActiveDistance        940 non-null    float64
dtypes: float64(4), int64(5), object(1)
memory usage: 73.6+ KB


 # Scaling: min-max normalization

In [63]:
import numpy as np
from sklearn import preprocessing

Numpy is a package for array manipulation. Sklearn is a source providing ML packages. 

In [64]:
# Define the features
fit_feat = fit.iloc[:,2:10]
fit_feat.head()

SedentaryMinutes  LightlyActiveMinutes  FairlyActiveMinutes  \
0               728                   328                   13   
1               776                   217                   19   
2              1218                   181                   11   
3               726                   209                   34   
4               773                   221                   10   

   VeryActiveMinutes  SedentaryActiveDistance  LightActiveDistance  \
0                 25                      0.0                 6.06   
1                 21                      0.0                 4.71   
2                 30                      0.0                 3.91   
3                 29                      0.0                 2.83   
4                 36                      0.0                 5.04   

   ModeratelyActiveDistance  VeryActiveDistance  
0                      0.55                1.88  
1                      0.69                1.57  
2                      0.40                2.44  
3                      1.26                2.14  
4                      0.41                2.71

In [65]:
# Min-max scaling
scaler = preprocessing.MinMaxScaler()
names = fit_feat.columns
aa = scaler.fit_transform(fit_feat)
scaled_df = pd.DataFrame(aa, columns=names)
scaled_df.head()

SedentaryMinutes  LightlyActiveMinutes  FairlyActiveMinutes  \
0          0.505556              0.633205             0.090909   
1          0.538889              0.418919             0.132867   
2          0.845833              0.349421             0.076923   
3          0.504167              0.403475             0.237762   
4          0.536806              0.426641             0.069930   

   VeryActiveMinutes  SedentaryActiveDistance  LightActiveDistance  \
0           0.119048                      0.0             0.565826   
1           0.100000                      0.0             0.439776   
2           0.142857                      0.0             0.365079   
3           0.138095                      0.0             0.264239   
4           0.171429                      0.0             0.470588   

   ModeratelyActiveDistance  VeryActiveDistance  
0                  0.084877            0.085766  
1                  0.106481            0.071624  
2                  0.061728            0.111314  
3                  0.194444            0.097628  
4                  0.063272            0.123631

In [66]:
aa

array([[0.50555556, 0.63320463, 0.09090909, ..., 0.56582632, 0.08487654,
        0.08576642],
       [0.53888889, 0.41891892, 0.13286713, ..., 0.43977591, 0.10648148,
        0.07162409],
       [0.84583333, 0.34942085, 0.07692308, ..., 0.36507937, 0.0617284 ,
        0.11131387],
       ...,
       [0.82430556, 0.43243243, 0.07692308, ..., 0.5863679 , 0.07098766,
        0.06158759],
       [0.78263889, 0.41119691, 0.08391608, ..., 0.5499533 , 0.0632716 ,
        0.6031022 ],
       [0.53472222, 0.26447876, 0.00699301, ..., 0.3968254 , 0.00617284,
        0.0830292 ]])

# Scaling to unit length

In [68]:
x_array = np.array([3,2,7])

In [69]:
normalized_arr = preprocessing.normalize([x_array])
print(normalized_arr)

[[0.38100038 0.25400025 0.88900089]]


In [70]:
# One variable from fit, convert to array
active_min = np.array(fit['SedentaryMinutes'])
active_min[0:10]

array([ 728,  776, 1218,  726,  773,  539, 1149,  775,  818,  838])

In [71]:
norm_min = preprocessing.normalize([active_min])
norm_min

array([[2.29210441e-02, 2.44323217e-02, 3.83486699e-02, 2.28580742e-02,
        2.43378668e-02, 1.69703884e-02, 3.61762083e-02, 2.44008367e-02,
        2.57546896e-02, 2.63843886e-02, 3.83171849e-02, 2.30469839e-02,
        2.23228300e-02, 2.56287498e-02, 2.62269639e-02, 3.48853253e-02,
        2.46212314e-02, 2.56602348e-02, 2.24172849e-02, 2.29840140e-02,
        2.51249906e-02, 2.56917197e-02, 3.71207568e-02, 2.69826027e-02,
        2.37396528e-02, 2.62269639e-02, 1.80723617e-02, 2.62899338e-02,
        2.34877732e-02, 2.10634320e-02, 4.53383289e-02, 4.07415261e-02,
        4.06785562e-02, 3.79078806e-02, 4.23157737e-02, 3.97969776e-02,
        4.01747970e-02, 3.82227301e-02, 4.08989509e-02, 4.05841014e-02,
        3.94821281e-02, 3.90728237e-02, 3.81912451e-02, 3.84431247e-02,
        3.89783689e-02, 4.09304358e-02, 3.88209441e-02, 4.15601348e-02,
        4.06155863e-02, 3.72152117e-02, 3.21146497e-02, 3.97025228e-02,
        4.23157737e-02, 4.16231047e-02, 4.16545897e-02, 4.212686

In [72]:
# More than one columns
fit_feat.head()

SedentaryMinutes  LightlyActiveMinutes  FairlyActiveMinutes  \
0               728                   328                   13   
1               776                   217                   19   
2              1218                   181                   11   
3               726                   209                   34   
4               773                   221                   10   

   VeryActiveMinutes  SedentaryActiveDistance  LightActiveDistance  \
0                 25                      0.0                 6.06   
1                 21                      0.0                 4.71   
2                 30                      0.0                 3.91   
3                 29                      0.0                 2.83   
4                 36                      0.0                 5.04   

   ModeratelyActiveDistance  VeryActiveDistance  
0                      0.55                1.88  
1                      0.69                1.57  
2                      0.40                2.44  
3                      1.26                2.14  
4                      0.41                2.71

In [73]:
names = fit_feat.columns
g = preprocessing.normalize(fit_feat)
scaled_df_norm = pd.DataFrame(g, columns=names)
scaled_df_norm.head()

SedentaryMinutes  LightlyActiveMinutes  FairlyActiveMinutes  \
0          0.911138              0.410513             0.016270   
1          0.962441              0.269136             0.023565   
2          0.988798              0.146940             0.008930   
3          0.959284              0.276158             0.044925   
4          0.960416              0.274582             0.012425   

   VeryActiveMinutes  SedentaryActiveDistance  LightActiveDistance  \
0           0.031289                      0.0             0.007584   
1           0.026045                      0.0             0.005842   
2           0.024355                      0.0             0.003174   
3           0.038319                      0.0             0.003739   
4           0.044728                      0.0             0.006262   

   ModeratelyActiveDistance  VeryActiveDistance  
0                  0.000688            0.002353  
1                  0.000856            0.001947  
2                  0.000325            0.001981  
3                  0.001665            0.002828  
4                  0.000509            0.003367

Here the values are normalized along the rows, which can be very unintuitive. Normalizing along rows means that each individual sample is normalized instead of the features.

However, you can specify the axis while calling the method to normalize along a feature (column).

The value of axis parameter is set to 1 by default. If we change the value to 0, the process of normalization happens along a column.

In [74]:
names = fit_feat.columns
g = preprocessing.normalize(fit_feat, axis=0)
scaled_df_norm = pd.DataFrame(g, columns=names)
scaled_df_norm.head()

SedentaryMinutes  LightlyActiveMinutes  FairlyActiveMinutes  \
0          0.022921              0.048288             0.017560   
1          0.024432              0.031947             0.025664   
2          0.038349              0.026647             0.014858   
3          0.022858              0.030769             0.045925   
4          0.024338              0.032536             0.013507   

   VeryActiveMinutes  SedentaryActiveDistance  LightActiveDistance  \
0           0.020877                      0.0             0.050497   
1           0.017536                      0.0             0.039248   
2           0.025052                      0.0             0.032581   
3           0.024217                      0.0             0.023582   
4           0.030062                      0.0             0.041998   

   ModeratelyActiveDistance  VeryActiveDistance  
0                  0.017089            0.020085  
1                  0.021439            0.016773  
2                  0.012428            0.026068  
3                  0.039149            0.022863  
4                  0.012739            0.028952

# Exercise  

Please open the file of dailyActivity_merged from FitBit [Fitness Tracker Data](https://www.kaggle.com/datasets/nurudeenabdulsalaam/fitbit-fitness-tracker-data?select=dailyActivity_merged.csv):
1. Normalized the numeric data using min-max normalizatio
2. Normalized the numeric data using scaling-to-unit-length (L2 norm)
3. Normalized the numeric data using standardization

In [75]:
act = pd.read_csv("dailyActivity_merged.csv")
act.head()

Id ActivityDate  TotalSteps  TotalDistance  TrackerDistance  \
0  1503960366    4/12/2016       13162           8.50             8.50   
1  1503960366    4/13/2016       10735           6.97             6.97   
2  1503960366    4/14/2016       10460           6.74             6.74   
3  1503960366    4/15/2016        9762           6.28             6.28   
4  1503960366    4/16/2016       12669           8.16             8.16   

   LoggedActivitiesDistance  VeryActiveDistance  ModeratelyActiveDistance  \
0                       0.0                1.88                      0.55   
1                       0.0                1.57                      0.69   
2                       0.0                2.44                      0.40   
3                       0.0                2.14                      1.26   
4                       0.0                2.71                      0.41   

   LightActiveDistance  SedentaryActiveDistance  VeryActiveMinutes  \
0                 6.06                      0.0                 25   
1                 4.71                      0.0                 21   
2                 3.91                      0.0                 30   
3                 2.83                      0.0                 29   
4                 5.04                      0.0                 36   

   FairlyActiveMinutes  LightlyActiveMinutes  SedentaryMinutes  Calories  
0                   13                   328               728      1985  
1                   19                   217               776      1797  
2                   11                   181              1218      1776  
3                   34                   209               726      1745  
4                   10                   221               773      1863

In [76]:
act.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 940 entries, 0 to 939
Data columns (total 15 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   Id                        940 non-null    int64  
 1   ActivityDate              940 non-null    object 
 2   TotalSteps                940 non-null    int64  
 3   TotalDistance             940 non-null    float64
 4   TrackerDistance           940 non-null    float64
 5   LoggedActivitiesDistance  940 non-null    float64
 6   VeryActiveDistance        940 non-null    float64
 7   ModeratelyActiveDistance  940 non-null    float64
 8   LightActiveDistance       940 non-null    float64
 9   SedentaryActiveDistance   940 non-null    float64
 10  VeryActiveMinutes         940 non-null    int64  
 11  FairlyActiveMinutes       940 non-null    int64  
 12  LightlyActiveMinutes      940 non-null    int64  
 13  SedentaryMinutes          940 non-null    int64  
 14  Calories  

In [77]:
act_fix = act.iloc[:,2:]
act_fix.head()

TotalSteps  TotalDistance  TrackerDistance  LoggedActivitiesDistance  \
0       13162           8.50             8.50                       0.0   
1       10735           6.97             6.97                       0.0   
2       10460           6.74             6.74                       0.0   
3        9762           6.28             6.28                       0.0   
4       12669           8.16             8.16                       0.0   

   VeryActiveDistance  ModeratelyActiveDistance  LightActiveDistance  \
0                1.88                      0.55                 6.06   
1                1.57                      0.69                 4.71   
2                2.44                      0.40                 3.91   
3                2.14                      1.26                 2.83   
4                2.71                      0.41                 5.04   

   SedentaryActiveDistance  VeryActiveMinutes  FairlyActiveMinutes  \
0                      0.0                 25                   13   
1                      0.0                 21                   19   
2                      0.0                 30                   11   
3                      0.0                 29                   34   
4                      0.0                 36                   10   

   LightlyActiveMinutes  SedentaryMinutes  Calories  
0                   328               728      1985  
1                   217               776      1797  
2                   181              1218      1776  
3                   209               726      1745  
4                   221               773      1863

### 2. Scale to unit length

In [78]:
names = act_fix.columns
g = preprocessing.normalize(act_fix, axis=0)
scaled_df_norm = pd.DataFrame(g, columns=names)
scaled_df_norm.head()

TotalSteps  TotalDistance  TrackerDistance  LoggedActivitiesDistance  \
0    0.046787       0.041090         0.041223                       0.0   
1    0.038160       0.033694         0.033803                       0.0   
2    0.037183       0.032582         0.032688                       0.0   
3    0.034701       0.030359         0.030457                       0.0   
4    0.045035       0.039447         0.039574                       0.0   

   VeryActiveDistance  ModeratelyActiveDistance  LightActiveDistance  \
0            0.020085                  0.017089             0.050497   
1            0.016773                  0.021439             0.039248   
2            0.026068                  0.012428             0.032581   
3            0.022863                  0.039149             0.023582   
4            0.028952                  0.012739             0.041998   

   SedentaryActiveDistance  VeryActiveMinutes  FairlyActiveMinutes  \
0                      0.0           0.020877             0.017560   
1                      0.0           0.017536             0.025664   
2                      0.0           0.025052             0.014858   
3                      0.0           0.024217             0.045925   
4                      0.0           0.030062             0.013507   

   LightlyActiveMinutes  SedentaryMinutes  Calories  
0              0.048288          0.022921  0.026833  
1              0.031947          0.024432  0.024291  
2              0.026647          0.038349  0.024008  
3              0.030769          0.022858  0.023589  
4              0.032536          0.024338  0.025184

### 3. Standardization

In [79]:
# define the function
scaler = preprocessing.StandardScaler()

# fit and transform the data
scaled_data = scaler.fit_transform(act_fix) 
scaled_data_df = pd.DataFrame(scaled_data, columns=act_fix.columns)
scaled_data_df.head()

TotalSteps  TotalDistance  TrackerDistance  LoggedActivitiesDistance  \
0    1.086469       0.767440         0.774519                 -0.174591   
1    0.609130       0.377385         0.382733                 -0.174591   
2    0.555044       0.318749         0.323837                 -0.174591   
3    0.417762       0.201477         0.206046                 -0.174591   
4    0.989506       0.680761         0.687455                 -0.174591   

   VeryActiveDistance  ModeratelyActiveDistance  LightActiveDistance  \
0            0.141981                 -0.019864             1.333213   
1            0.025332                  0.138666             0.671309   
2            0.352704                 -0.189719             0.279069   
3            0.239817                  0.784112            -0.250454   
4            0.454302                 -0.178395             0.833108   

   SedentaryActiveDistance  VeryActiveMinutes  FairlyActiveMinutes  \
0                -0.218786           0.116827            -0.028278   
1                -0.218786          -0.005023             0.272071   
2                -0.218786           0.269139            -0.128394   
3                -0.218786           0.238676             1.022943   
4                -0.218786           0.451913            -0.178452   

   LightlyActiveMinutes  SedentaryMinutes  Calories  
0              1.238924         -0.874143 -0.443879  
1              0.221664         -0.714731 -0.705796  
2             -0.108258          0.753185 -0.735053  
3              0.148348         -0.880785 -0.778241  
4              0.258322         -0.724694 -0.613846

In [80]:
# The mean of scaled data (each column, should be around 0)
scaled_data.mean(axis = 0)

array([-4.53537916e-17, -9.07075833e-17,  4.53537916e-17,  3.02358611e-17,
       -4.53537916e-17, -1.09604996e-16,  1.43620340e-16, -4.15743090e-17,
       -3.02358611e-17,  1.88974132e-17,  6.80306875e-17, -1.36061375e-16,
       -6.04717222e-17])

In [81]:
# The standar deviation of each column
scaled_data.std(axis = 0)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])